### ISSUE TITLE
It may meet the "nan" loss when running the train-base.py function?

### ISSUE THREAD

**Issue by FreedStar** [nayeemrizve/OpenLDN#4]
When I run the OpenLDN method on CIFAR-100 dataset (the default setting), I meet the "nan" loss. Have you ever encountered this problem before? How should I work out with it?

python train.py --dataset cifar100 --lbl-percent 50 --novel-percent 50 --arch resnet18

train epoch: 2/  50. itr:  345/ 370. btime: 0.468s. loss: 3434385621372.6826. l_ce: 14.8801. l_pair: 3434385621361.5322. l_reg: 3.6790:  93%|█████████▎| 344/370 [02:41<train epoch: 2/  50. itr:  345/ 370. btime: 0.468s. loss: 3434385621372.6826. l_ce: 14.8801. l_pair: 3434385621361.5322. l_reg: 3.6790:  93%|█████████▎| 345/370 [02:41<train epoch: 2/  50. itr:  346/ 370. btime: 0.468s. loss: nan. l_ce: nan. l_pair: nan. l_reg: nan:  93%|█████████▎| 345/370 [02:42<00:12,  2.08it/s]                    train epoch: 2/  50. itr:  370/ 370. btime: 0.469s. loss: nan. l_ce: nan. l_pair: nan. l_reg: nan: 100%|██████████| 370/370 [02:53<00:00,  2.13it/s]
test epoch: 2/  50. itr:   25/  25. btime: 0.089s. loss: nan. top1: 2.00. top5: 10.00. : 100%|██████████| 25/25 [00:02<00:00, 10.41it/s] 
test epoch: 2/  50. itr:   25/  25. btime: 0.077s.: 100%|██████████| 25/25 [00:02<00:00, 11.81it/s]
test epoch: 2/  50. itr:   50/  50. btime: 0.058s.: 100%|██████████| 50/50 [00:03<00:00, 15.94it/s]

...

Traceback (most recent call last):
  File "base/train-base.py", line 425, in <module>
    main()
  File "base/train-base.py", line 183, in main
    pl_dict, pl_acc, pl_no = pseudo_labeling(args, pl_loader, model, list(range(args.no_known, args.no_class)), no_pl_perclass)
  File "base/utils/pseudo_labeling_utils.py", line 64, in pseudo_labeling
    pseudo_target = pseudo_target[blnc_idx_list]
IndexError: arrays used as indices must be of integer (or boolean) type

**Comment by FreedStar** [comment]
We also find that OpenLDN needs very large GPU memory on some datasets, such as Standford Cars and ImageNet100 datasets. So can you give me more training details or optimize the codes? What is your GPU for experiments?

RuntimeError: CUDA out of memory. Tried to allocate 2.30 GiB (GPU 0; 79.10 GiB total capacity; 30.41 GiB already allocated; 1.37 GiB free; 32.80 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.

**Comment by nayeemrizve** [comment]
For the datasets with large input resolution (224x224), we have used ResNet-18 for the base model training. We have used 4x48GB GPUs for the base model training in such cases (because of the large memory footprint).
